# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["your@email.com"]
description = "Queue-it connector for Fastly"
language = "assemblyscript"
manifest_version = 1
name = "connector-fastly"
service_id = "{YourServiceId}"
